# Generated by Django 4.2.9 on 2024-01-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_login_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_id",
            field=models.IntegerField(unique=True),
        ),
    ]
