# Generated by Django 4.2.9 on 2024-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("style", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
                ("is_deleted", models.DateField()),
            ],
        ),
    ]
