# Generated by Django 4.2.9 on 2024-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="position",
            field=models.CharField(
                choices=[
                    ("frontend", "FRONTEND"),
                    ("backend", "BACKEND"),
                    ("fullstack", "FULLSTACK"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="style",
            field=models.CharField(
                choices=[("video", "VIDEO"), ("voice", "VOICE"), ("text", "TEXT")],
                max_length=5,
            ),
        ),
    ]
