# Generated by Django 4.2.9 on 2024-01-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_login_id"),
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                to_field="login_id",
            ),
        ),
    ]
