# Generated by Django 4.2.9 on 2024-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_alter_interview_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="resume_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="interview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="interview",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="interview",
            name="position",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("fullstack", "FUllstack"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="style",
            field=models.CharField(
                choices=[
                    ("Video", "Video Interview"),
                    ("Voice", "Voice Interview"),
                    ("Text", "Text Interview"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
